apiVersion: v1
kind: PersistentVolume
metadata:
  name: tasks-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  hostPath:
    path: /tasks
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
